# Generated by Django 2.0.7 on 2018-08-04 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('currentPosition', models.IntegerField()),
                ('isPublic', models.BooleanField()),
                ('users', models.ManyToManyField(related_name='chains', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='web.Chain')),
                ('user', models.ForeignKey(default='[Deleted User]', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='phrases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('data', models.ImageField(upload_to='images/%Y/%m')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='web.Chain')),
                ('user', models.ForeignKey(default='[Deleted User]', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pictures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
