# Generated by Django 2.0.7 on 2018-08-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
