# Generated by Django 2.0.7 on 2018-08-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_chain_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
