# Generated by Django 2.0.7 on 2018-08-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180806_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='isOpen',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chain',
            name='maxUsers',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
