# Generated by Django 2.0.7 on 2018-08-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180806_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
