# Generated by Django 2.0.7 on 2018-08-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180806_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='currentPosition',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chain',
            name='isOpen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
