# Generated by Django 2.0.7 on 2018-08-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20180808_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
