# Generated by Django 2.0.7 on 2018-08-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20180808_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
